/*
 * Bindings for CSP/Common/SharedEnums.h.
 */

#include "CSP/Common/SharedEnums.h"

#include "emscripten/bind.h"

EMSCRIPTEN_BINDINGS(CSPSharedEnums)
{
    emscripten::enum_<csp::web::EResponseCodes>("EResponseCodes", emscripten::enum_value_type::number)
        .value("ResponseInit", csp::web::EResponseCodes::ResponseInit)
        .value("ResponseContinue", csp::web::EResponseCodes::ResponseContinue)
        .value("ResponseSwitchingProtocols", csp::web::EResponseCodes::ResponseSwitchingProtocols)
        .value("ResponseProcessing", csp::web::EResponseCodes::ResponseProcessing)
        .value("ResponseOK", csp::web::EResponseCodes::ResponseOK)
        .value("ResponseCreated", csp::web::EResponseCodes::ResponseCreated)
        .value("ResponseAccepted", csp::web::EResponseCodes::ResponseAccepted)
        .value("ResponseNonauthoritative", csp::web::EResponseCodes::ResponseNonauthoritative)
        .value("ResponseNoContent", csp::web::EResponseCodes::ResponseNoContent)
        .value("ResponseResetContent", csp::web::EResponseCodes::ResponseResetContent)
        .value("ResponsePartialContent", csp::web::EResponseCodes::ResponsePartialContent)
        .value("ResponseMultiStatus", csp::web::EResponseCodes::ResponseMultiStatus)
        .value("ResponseAlreadyReported", csp::web::EResponseCodes::ResponseAlreadyReported)
        .value("ResponseImUsed", csp::web::EResponseCodes::ResponseImUsed)
        .value("ResponseMultipleChoices", csp::web::EResponseCodes::ResponseMultipleChoices)
        .value("ResponseMovedPermanently", csp::web::EResponseCodes::ResponseMovedPermanently)
        .value("ResponseFound", csp::web::EResponseCodes::ResponseFound)
        .value("ResponseSeeOther", csp::web::EResponseCodes::ResponseSeeOther)
        .value("ResponseNotModified", csp::web::EResponseCodes::ResponseNotModified)
        .value("ResponseUseProxy", csp::web::EResponseCodes::ResponseUseProxy)
        .value("ResponseTemporaryRedirect", csp::web::EResponseCodes::ResponseTemporaryRedirect)
        .value("ResponsePermanentRedirect", csp::web::EResponseCodes::ResponsePermanentRedirect)
        .value("ResponseBadRequest", csp::web::EResponseCodes::ResponseBadRequest)
        .value("ResponseUnauthorized", csp::web::EResponseCodes::ResponseUnauthorized)
        .value("ResponsePaymentRequired", csp::web::EResponseCodes::ResponsePaymentRequired)
        .value("ResponseForbidden", csp::web::EResponseCodes::ResponseForbidden)
        .value("ResponseNotFound", csp::web::EResponseCodes::ResponseNotFound)
        .value("ResponseMethodNotAllowed", csp::web::EResponseCodes::ResponseMethodNotAllowed)
        .value("ResponseNotAcceptable", csp::web::EResponseCodes::ResponseNotAcceptable)
        .value("ResponseProxyAuthenticationRequired", csp::web::EResponseCodes::ResponseProxyAuthenticationRequired)
        .value("ResponseRequestTimeout", csp::web::EResponseCodes::ResponseRequestTimeout)
        .value("ResponseConflict", csp::web::EResponseCodes::ResponseConflict)
        .value("ResponseGone", csp::web::EResponseCodes::ResponseGone)
        .value("ResponseLengthRequired", csp::web::EResponseCodes::ResponseLengthRequired)
        .value("ResponsePreconditionFailed", csp::web::EResponseCodes::ResponsePreconditionFailed)
        .value("ResponseRequestEntityTooLarge", csp::web::EResponseCodes::ResponseRequestEntityTooLarge)
        .value("ResponseRequestUriTooLong", csp::web::EResponseCodes::ResponseRequestUriTooLong)
        .value("ResponseUnsupportedMediaType", csp::web::EResponseCodes::ResponseUnsupportedMediaType)
        .value("ResponseRequestedRangeNotSatisfiable", csp::web::EResponseCodes::ResponseRequestedRangeNotSatisfiable)
        .value("ResponseExpectationFailed", csp::web::EResponseCodes::ResponseExpectationFailed)
        .value("ResponseImATeapot", csp::web::EResponseCodes::ResponseImATeapot)
        .value("ResponseEnchanceYourCalm", csp::web::EResponseCodes::ResponseEnchanceYourCalm)
        .value("ResponseMisdirectedRequest", csp::web::EResponseCodes::ResponseMisdirectedRequest)
        .value("ResponseUnprocessableEntity", csp::web::EResponseCodes::ResponseUnprocessableEntity)
        .value("ResponseLocked", csp::web::EResponseCodes::ResponseLocked)
        .value("ResponseFailedDependency", csp::web::EResponseCodes::ResponseFailedDependency)
        .value("ResponseUpgradeRequired", csp::web::EResponseCodes::ResponseUpgradeRequired)
        .value("ResponsePreconditionRequired", csp::web::EResponseCodes::ResponsePreconditionRequired)
        .value("ResponseTooManyRequests", csp::web::EResponseCodes::ResponseTooManyRequests)
        .value("ResponseRequestHeaderFieldsTooLarge", csp::web::EResponseCodes::ResponseRequestHeaderFieldsTooLarge)
        .value("ResponseUnavailableForLegalReasons", csp::web::EResponseCodes::ResponseUnavailableForLegalReasons)
        .value("ResponseInternalServerError", csp::web::EResponseCodes::ResponseInternalServerError)
        .value("ResponseNotImplemented", csp::web::EResponseCodes::ResponseNotImplemented)
        .value("ResponseBadGateway", csp::web::EResponseCodes::ResponseBadGateway)
        .value("ResponseServiceUnavailable", csp::web::EResponseCodes::ResponseServiceUnavailable)
        .value("ResponseGatewayTimeout", csp::web::EResponseCodes::ResponseGatewayTimeout)
        .value("ResponseVersionNotSupported", csp::web::EResponseCodes::ResponseVersionNotSupported)
        .value("ResponseVariantAlsoNegotiates", csp::web::EResponseCodes::ResponseVariantAlsoNegotiates)
        .value("ResponseInsufficientStorage", csp::web::EResponseCodes::ResponseInsufficientStorage)
        .value("ResponseLoopDetected", csp::web::EResponseCodes::ResponseLoopDetected)
        .value("ResponseNotExtended", csp::web::EResponseCodes::ResponseNotExtended)
        .value("ResponseNetworkAuthenticationRequired", csp::web::EResponseCodes::ResponseNetworkAuthenticationRequired);

    emscripten::enum_<csp::systems::EResultCode>("EResultCode", emscripten::enum_value_type::number)
        .value("Init", csp::systems::EResultCode::Init)
        .value("InProgress", csp::systems::EResultCode::InProgress)
        .value("Success", csp::systems::EResultCode::Success)
        .value("Failed", csp::systems::EResultCode::Failed);

    emscripten::enum_<csp::systems::ERequestFailureReason>("ERequestFailureReason", emscripten::enum_value_type::number)
        .value("Unknown", csp::systems::ERequestFailureReason::Unknown)
        .value("None", csp::systems::ERequestFailureReason::None)
        .value("AddUserToSpaceDenied", csp::systems::ERequestFailureReason::AddUserToSpaceDenied)
        .value("UserSpaceAccessDenied", csp::systems::ERequestFailureReason::UserSpaceAccessDenied)
        .value("UserSpaceBannedAccessDenied", csp::systems::ERequestFailureReason::UserSpaceBannedAccessDenied)
        .value("UserSpaceFullAccessDenied", csp::systems::ERequestFailureReason::UserSpaceFullAccessDenied)
        .value("UserSpaceInviteExpired", csp::systems::ERequestFailureReason::UserSpaceInviteExpired)
        .value("SpacePublicNameDuplicate", csp::systems::ERequestFailureReason::SpacePublicNameDuplicate)
        .value("UserMaxSpaceLimitReached", csp::systems::ERequestFailureReason::UserMaxSpaceLimitReached)
        .value("UserAccountLocked", csp::systems::ERequestFailureReason::UserAccountLocked)
        .value("UserMissingPassword", csp::systems::ERequestFailureReason::UserMissingPassword)
        .value("UserUnverifiedEmail", csp::systems::ERequestFailureReason::UserUnverifiedEmail)
        .value("UserBannedFromSpace", csp::systems::ERequestFailureReason::UserBannedFromSpace)
        .value("UserInvalidEmailDomain", csp::systems::ERequestFailureReason::UserInvalidEmailDomain)
        .value("UserInvalidThirdPartyAuth", csp::systems::ERequestFailureReason::UserInvalidThirdPartyAuth)
        .value("UserAgeNotVerified", csp::systems::ERequestFailureReason::UserAgeNotVerified)
        .value("UserGuestLoginDisallowed", csp::systems::ERequestFailureReason::UserGuestLoginDisallowed)
        .value("UserAgoraLimitReached", csp::systems::ERequestFailureReason::UserAgoraLimitReached)
        .value("UserOpenAILimitReached", csp::systems::ERequestFailureReason::UserOpenAILimitReached)
        .value("UserTicketedSpacesLimitReached", csp::systems::ERequestFailureReason::UserTicketedSpacesLimitReached)
        .value("UserSpaceConcurrentUsersLimitReached", csp::systems::ERequestFailureReason::UserSpaceConcurrentUsersLimitReached)
        .value("PrototypeReservedKeysNotAllowed", csp::systems::ERequestFailureReason::PrototypeReservedKeysNotAllowed)
        .value("AssetInvalidFileContents", csp::systems::ERequestFailureReason::AssetInvalidFileContents)
        .value("AssetInvalidFileType", csp::systems::ERequestFailureReason::AssetInvalidFileType)
        .value("AssetAudioVideoLimitReached", csp::systems::ERequestFailureReason::AssetAudioVideoLimitReached)
        .value("AssetObjectCaptureLimitReached", csp::systems::ERequestFailureReason::AssetObjectCaptureLimitReached)
        .value("AssetTotalUploadSizeLimitReached", csp::systems::ERequestFailureReason::AssetTotalUploadSizeLimitReached)
        .value("TicketUnknownNumber", csp::systems::ERequestFailureReason::TicketUnknownNumber)
        .value("TicketEmailMismatch", csp::systems::ERequestFailureReason::TicketEmailMismatch)
        .value("TicketVendorOAuthFailure", csp::systems::ERequestFailureReason::TicketVendorOAuthFailure)
        .value("TicketOAuthTokenInvalid", csp::systems::ERequestFailureReason::TicketOAuthTokenInvalid)
        .value("TicketAlreadyApplied", csp::systems::ERequestFailureReason::TicketAlreadyApplied)
        .value("ShopifyConnectionBroken", csp::systems::ERequestFailureReason::ShopifyConnectionBroken)
        .value("ShopifyInvalidStoreName", csp::systems::ERequestFailureReason::ShopifyInvalidStoreName)
        .value("UserShopifyLimitReached", csp::systems::ERequestFailureReason::UserShopifyLimitReached)
        .value("UserTokenRefreshFailed", csp::systems::ERequestFailureReason::UserTokenRefreshFailed)
        .value("InvalidSequenceKey", csp::systems::ERequestFailureReason::InvalidSequenceKey);

    emscripten::enum_<csp::common::ELoginState>("ELoginState", emscripten::enum_value_type::number)
        .value("LoginRequested", csp::common::ELoginState::LoginRequested)
        .value("LoggedIn", csp::common::ELoginState::LoggedIn)
        .value("LogoutRequested", csp::common::ELoginState::LogoutRequested)
        .value("LoggedOut", csp::common::ELoginState::LoggedOut)
        .value("Error", csp::common::ELoginState::Error);

    emscripten::enum_<csp::multiplayer::AvatarState>("AvatarState", emscripten::enum_value_type::number)
        .value("Idle", csp::multiplayer::AvatarState::Idle)
        .value("Walking", csp::multiplayer::AvatarState::Walking)
        .value("Running", csp::multiplayer::AvatarState::Running)
        .value("Flying", csp::multiplayer::AvatarState::Flying)
        .value("Jumping", csp::multiplayer::AvatarState::Jumping)
        .value("Falling", csp::multiplayer::AvatarState::Falling)
        .value("Num", csp::multiplayer::AvatarState::Num);

    emscripten::enum_<csp::multiplayer::AvatarPlayMode>("AvatarPlayMode", emscripten::enum_value_type::number)
        .value("Default", csp::multiplayer::AvatarPlayMode::Default)
        .value("AR", csp::multiplayer::AvatarPlayMode::AR)
        .value("VR", csp::multiplayer::AvatarPlayMode::VR)
        .value("Creator", csp::multiplayer::AvatarPlayMode::Creator)
        .value("Num", csp::multiplayer::AvatarPlayMode::Num);

    emscripten::enum_<csp::multiplayer::LocomotionModel>("LocomotionModel", emscripten::enum_value_type::number)
        .value("Grounded", csp::multiplayer::LocomotionModel::Grounded)
        .value("FreeCamera", csp::multiplayer::LocomotionModel::FreeCamera)
        .value("Num", csp::multiplayer::LocomotionModel::Num);

    emscripten::enum_<csp::multiplayer::ErrorCode>("ErrorCode", emscripten::enum_value_type::number)
        .value("None", csp::multiplayer::ErrorCode::None)
        .value("Unknown", csp::multiplayer::ErrorCode::Unknown)
        .value("NotConnected", csp::multiplayer::ErrorCode::NotConnected)
        .value("AlreadyConnected", csp::multiplayer::ErrorCode::AlreadyConnected)
        .value("SpaceUserLimitExceeded", csp::multiplayer::ErrorCode::SpaceUserLimitExceeded);

    emscripten::enum_<csp::multiplayer::ModifiableStatus>("ModifiableStatus", emscripten::enum_value_type::number)
        .value("Modifiable", csp::multiplayer::ModifiableStatus::Modifiable)
        .value("EntityLocked", csp::multiplayer::ModifiableStatus::EntityLocked)
        .value("EntityNotOwnedAndUntransferable", csp::multiplayer::ModifiableStatus::EntityNotOwnedAndUntransferable);

    emscripten::enum_<csp::multiplayer::StereoVideoType>("StereoVideoType", emscripten::enum_value_type::number)
        .value("None", csp::multiplayer::StereoVideoType::None)
        .value("SideBySide", csp::multiplayer::StereoVideoType::SideBySide)
        .value("TopBottom", csp::multiplayer::StereoVideoType::TopBottom);

    emscripten::enum_<csp::systems::EThirdPartyPlatform>("EThirdPartyPlatform", emscripten::enum_value_type::number)
        .value("None", csp::systems::EThirdPartyPlatform::None)
        .value("Unreal", csp::systems::EThirdPartyPlatform::Unreal)
        .value("Unity", csp::systems::EThirdPartyPlatform::Unity)
        .value("Web", csp::systems::EThirdPartyPlatform::Web);
}
