#pragma once

#include "emscripten/val.h"

/*
 * Val types for Promises the bindings expose.
 * Typescript sigs are defined in PromiseDeclarations.cpp
 */

EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfBoolean);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfSpaceEntityPointer);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfErrorCode);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfNullResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfStringResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfMessageResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfMessageCollectionResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfConversationResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfNumberOfRepliesResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAnnotationResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAnnotationThumbnailCollectionResult);

EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfBooleanResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfStringArrayResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfUInt64Result);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAssetResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAssetsResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfUriResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAssetDataResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAssetCollectionResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAssetCollectionsResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAssetCollectionCountResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfLODChainResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfMaterialResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfMaterialsResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfSpaceResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfSpacesResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfBasicSpaceResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfBasicSpacesResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfSpaceMetadataResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfSpacesMetadataResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfPendingInvitesResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAcceptedInvitesResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfSpaceGeoLocationResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfSiteResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfSitesCollectionResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfUserRoleCollectionResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfProfileResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfBasicProfilesResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfLoginStateResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfFeaturesLimitResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfFeatureLimitResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfUserTierResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfFeatureQuotaResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfFeaturesQuotaResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfSequenceResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfSequencesResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfHotspotGroupResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfHotspotGroupsResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfTicketedEventResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfTicketedEventCollectionResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfEventTicketResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfSpaceIsTicketedResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfTicketedEventVendorAuthInfoResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfGraphQLResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfMaintenanceInfoResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfProductInfoResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfProductInfoCollectionResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfCheckoutInfoResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfCartInfoResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAddShopifyStoreResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfValidateShopifyStoreResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfGetShopifyStoresResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfApplicationSettingsResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAvatarInfoResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAnchorResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAnchorCollectionResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfAnchorResolutionResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfPOIResult);
EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseOfPOICollectionResult);
