#pragma once

#include "Callbacks.h"
#include "emscripten/bind.h"
#include "emscripten/emscripten.h"
#include "emscripten/val.h"

extern "C" emscripten::EM_VAL make_promise_with_cloning_callback(emscripten::EM_VAL progressCallbackHandle);

namespace {

/*
 * Utility for converting a C++ function that takes a callback into a function that returns a
 * JavaScript Promise.
 *
 * Given a C++ function that accepts a callback, such as:
 *
 *   void func(std::function<void(int)> callback);
 *
 * Promisify is used to turn it into a promise-returning function on the JavaScript side:
 *
 *   function funcAsync(): Promise<number>;
 *
 * Example usage with the above C++ function:
 *
 *   EMSCRIPTEN_BINDINGS(...) {
 *     emscripten::function("funcAsync", +[]()
 *     {
 *       return Promisify<PromiseNumberValType>(
 *         [](emscripten::val cb) { func(ToNativeCallback(cb.as<FuncCallbackJSType>())) }
 *       );
 *     });
 *   }
 *
 * A few notes on the usage above:
 *  - ToNativeCallback and FuncCallbackJSType are generated by the MAKE_CALLBACK macro which must be
 *    used prior to this binding code. See Callbacks.h for more details.
 *  - PromiseNumberValType is a specialised Embind val type that must also be declared prior to this
 *    binding code. This will be the return type of the bound function in TypeScript.
 *    In this example it would be declared as:
 *
 *      EMSCRIPTEN_DECLARE_VAL_TYPE(PromiseNumberValType);
 *      EMSCRIPTEN_BINDINGS(register_PromiseNumberValType)
 *      {
 *        emscripten::register_type<PromiseNumberValType>("Promise<number>");
 *      }
 *
 * Promisify has native support for C++ functions using ResultBase-derived types as the callback
 * parameter. In this case the promise will resolve if the result is successful, and reject if the
 * result is a failure. An optional progress callback can also be provided to Promisify which will
 * be called with progress updates if the C++ function reports in-progress results.
 * For non-ResultBase values, the promise will be resolved with the callback parameter.
 *
 * The JS callback that the bound C++ function ultimately calls (`jsCallback`) will perform an
 * additional clone of the callback argument before resolving the promise. This is required because
 * Promisify is designed to be used with the existing ToNativeCallback machinery which will
 * automatically dispose of the callback argument after the callback returns. The clone ensures the
 * argument is kept alive, but means that the user must dispose the argument themselves.
 *
 * Template parameters:
 *     PromiseValType: Specialised Embind val type corresponding to the return type of the function
 *                     in TypeScript. Defaults to emscripten::val (which will appear as 'any' in the
 *                     TypeScript definitions).
 *     WrapperFn: Callable that takes an emscripten::val (the JS callback) and invokes the original
 *                C++ function with the JS callback, via ToNativeCallback.
 *
 * Parameters:
 *     wrapperFn: Callable that takes an emscripten::val (the JS callback) and invokes the original
 *                C++ function, passing in the JS callback, via ToNativeCallback.
 *     progressCallback: Optional emscripten::val representing a JavaScript function that will be
 *                       called with progress updates. This is used when promisify-ing C++ functions
 *                       based on ResultBase that report progress.
 */
template <typename PromiseValType = emscripten::val, typename WrapperFn>
inline PromiseValType Promisify(WrapperFn&& wrapperFn, emscripten::val progressCallback = emscripten::val::undefined())
{
    emscripten::val promiseAndCallback = emscripten::val::take_ownership(make_promise_with_cloning_callback(progressCallback.as_handle()));
    // This is the JS callback that the C++ function will ultimately call, and is responsible for
    // resolving the promise.
    emscripten::val jsCallback = promiseAndCallback["callback"];

    // Call the original C++ function, passing through our JS callback
    wrapperFn(jsCallback);

    emscripten::val promise = promiseAndCallback["promise"];

    return PromiseValType(std::move(promise));
}

} // namespace
